name: Main Branch Protection
description: Protects the main branch with required reviews, status checks, and security policies
enforcement: active
targets:
  branches:
    - main
rules:
  # Require pull request reviews before merging
  - name: Require pull request reviews before merging
    parameters:
      required_approving_review_count: 1
      dismiss_stale_reviews_on_push: true
      require_code_owner_reviews: false
      require_last_push_approval: false
      required_reviewer_count: 0
      bypass_pull_request_allowances:
        users: []
        teams: []
        apps: []
  
  # Require status checks to pass before merging
  - name: Require status checks to pass before merging
    parameters:
      required_status_checks:
        strict: true
        contexts: []
      required_status_checks_evaluation: latest
  
  # Require conversation resolution before merging
  - name: Require conversation resolution before merging
    parameters: {}
  
  # Require signed commits
  - name: Require signed commits
    parameters: {}
  
  # Require linear history
  - name: Require linear history
    parameters: {}
  
  # Require deployments to succeed before merging
  - name: Require deployments to succeed before merging
    parameters:
      required_deployment_environments: []
  
  # Lock branch
  - name: Lock branch
    parameters: {}
  
  # Do not allow bypassing the above settings
  - name: Do not allow bypassing the above settings
    parameters:
      bypass_pull_request_allowances:
        users: []
        teams: []
        apps: []
      bypass_force_push_allowances:
        users: []
        teams: []
        apps: []
      bypass_deletion_allowances:
        users: []
        teams: []
        apps: [] 