name: Security Policy
description: Security-focused rules to prevent common vulnerabilities and maintain code quality
enforcement: active
targets:
  branches:
    - main
rules:
  # Prevent secret scanning alerts from being merged
  - name: Prevent secret scanning alerts from being merged
    parameters: {}
  
  # Prevent dependency review alerts from being merged
  - name: Prevent dependency review alerts from being merged
    parameters: {}
  
  # Require security policy
  - name: Require security policy
    parameters: {}
  
  # Require security and analysis features to be enabled
  - name: Require security and analysis features to be enabled
    parameters:
      required_status_checks:
        strict: true
        contexts:
          - "Secret scanning"
          - "Dependency review"
          - "Code scanning" 